spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: {YOUR_GMAIL_ADDRESS}
    password: {YOUR_GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/sadang
    username: jun
    password: 1234
