spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sadang
    username: jun
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

  jwt:
    secret: asdfasdklfkljsdflkjsdalfjbvklvcb
  mail:
    host: smtp.gmail.com
    port: 587
    username: 유저id
    password: 유저비밀번호
    properties:
      mail:
        smtp:
          auth: true;
          starttls:
            enable: true;
