spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sadang
    username: jun
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
